/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v7.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 7.0.1
board: MIMXRT1010-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 753cac3e-e8e5-4e48-ae69-afc827b7af98
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_1d2abaef2e6117c98d396751e1792fd5'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - enableRoundRobinArbitration: 'false'
      - enableDebugMode: 'false'
    - dma_table:
      - 0: []
      - 1: []
    - edma_channels:
      - 0:
        - apiMode: 'nontrans'
        - edma_channel:
          - channel_prefix_id: 'CH0'
          - eDMAn: '0'
          - eDMA_source: 'kDmaRequestMuxLPSPI1Tx'
          - enableTriggerPIT: 'false'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
        - resetChannel: 'false'
        - enableChannelRequest: 'false'
        - enableAsyncRequest: 'false'
        - enableAutoStop: 'false'
        - enableMinorLoop: 'false'
        - minorLoopConfig:
          - offsetType: 'disabled'
          - mloff: '0'
        - init_channel_link: 'false'
        - channel_link: 'kEDMA_LinkNone'
        - linkedChannel: ''
        - init_bandwidth: 'false'
        - bandwidth: 'kEDMA_BandwidthStallNone'
        - init_modulo: 'false'
        - s_mod: 'kEDMA_ModuloDisable'
        - d_mod: 'kEDMA_ModuloDisable'
        - nontransEnable: 'false'
        - nontrans_config:
          - tcdID: 'CH0_transfer'
          - saddr_expr: ''
          - saddr_def: ''
          - soff: '0U'
          - soff_def: ''
          - ssize: 'kEDMA_TransferSize1Bytes'
          - daddr_expr: ''
          - daddr_def: ''
          - doff: '0U'
          - doff_def: ''
          - dsize: 'kEDMA_TransferSize1Bytes'
          - nbytes: '1'
        - channel_enabled_interrupts: ''
        - init_interrupts: 'false'
        - interrupt_channel:
          - IRQn: 'DMA0_IRQn'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 1:
        - apiMode: 'nontrans'
        - edma_channel:
          - channel_prefix_id: 'CH1'
          - eDMAn: '1'
          - eDMA_source: 'kDmaRequestMuxLPSPI1Rx'
          - enableTriggerPIT: 'false'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
        - resetChannel: 'false'
        - enableChannelRequest: 'false'
        - enableAsyncRequest: 'false'
        - enableAutoStop: 'false'
        - enableMinorLoop: 'false'
        - minorLoopConfig:
          - offsetType: 'disabled'
          - mloff: '0'
        - init_channel_link: 'false'
        - channel_link: 'kEDMA_LinkNone'
        - linkedChannel: '0'
        - init_bandwidth: 'false'
        - bandwidth: 'kEDMA_BandwidthStallNone'
        - init_modulo: 'false'
        - s_mod: 'kEDMA_ModuloDisable'
        - d_mod: 'kEDMA_ModuloDisable'
        - nontransEnable: 'false'
        - nontrans_config:
          - tcdID: 'CH1_transfer'
          - saddr_expr: ''
          - saddr_def: ''
          - soff: '0U'
          - soff_def: ''
          - ssize: 'kEDMA_TransferSize1Bytes'
          - daddr_expr: ''
          - daddr_def: ''
          - doff: '0U'
          - doff_def: ''
          - dsize: 'kEDMA_TransferSize1Bytes'
          - nbytes: '1'
        - channel_enabled_interrupts: ''
        - init_interrupts: 'false'
        - interrupt_channel:
          - IRQn: 'DMA1_IRQn'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_ERROR_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA0_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

void DMA0_init(void) {

  /* Channel CH0 initialization */
  /* Set the source kDmaRequestMuxLPSPI1Tx request in the DMAMUX */
  DMAMUX_SetSource(DMA0_DMAMUX_BASEADDR, DMA0_CH0_DMA_CHANNEL, DMA0_CH0_DMA_REQUEST);
  /* Enable the 0 channel in the DMAMUX */
  DMAMUX_EnableChannel(DMA0_DMAMUX_BASEADDR, DMA0_CH0_DMA_CHANNEL);

  /* Channel CH1 initialization */
  /* Set the source kDmaRequestMuxLPSPI1Rx request in the DMAMUX */
  DMAMUX_SetSource(DMA0_DMAMUX_BASEADDR, DMA0_CH1_DMA_CHANNEL, DMA0_CH1_DMA_REQUEST);
  /* Enable the 1 channel in the DMAMUX */
  DMAMUX_EnableChannel(DMA0_DMAMUX_BASEADDR, DMA0_CH1_DMA_CHANNEL);
}

/***********************************************************************************************************************
 * FLEXIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXIO1'
- type: 'flexio_spi'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'flexio_spi_d67d6584d62b130dba246fa5abb61949'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXIO1'
- config_sets:
  - fsl_flexio_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FlexIoClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - peripheralConfig:
      - SDOPinIndex: '1'
      - SDIPinIndex: '2'
      - SCKPinIndex: '21'
      - CSnPinIndex: '22'
      - shifterIndex_0: '0'
      - shifterIndex_1: '2'
      - timerIndex_0: '0'
      - timerIndex_1: '1'
    - master_config:
      - enableMaster: 'true'
      - enableInDoze: 'true'
      - enableInDebug: 'true'
      - enableFastAccess: 'true'
      - baudRate_Bps: '5000000'
      - phase: 'kFLEXIO_SPI_ClockPhaseFirstEdge'
      - dataMode: 'kFLEXIO_SPI_8BitMode'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'true'
      - interrupt:
        - IRQn: 'FLEXIO1_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* FlexIO access configuration */
FLEXIO_SPI_Type FLEXIO1_peripheralConfig = {
  .flexioBase = FLEXIO1_PERIPHERAL,
  .SDOPinIndex = 1,
  .SDIPinIndex = 2,
  .SCKPinIndex = 21,
  .CSnPinIndex = 22,
  .shifterIndex = {0, 2},
  .timerIndex = {0, 1}
};
/* SPI master configuration */
flexio_spi_master_config_t FLEXIO1_config = {
  .enableMaster = true,
  .enableInDoze = true,
  .enableInDebug = true,
  .enableFastAccess = true,
  .baudRate_Bps = 5000000,
  .phase = kFLEXIO_SPI_ClockPhaseFirstEdge,
  .dataMode = kFLEXIO_SPI_8BitMode
};

void FLEXIO1_init(void) {
  /* Master initialization */
  FLEXIO_SPI_MasterInit(&FLEXIO1_peripheralConfig, &FLEXIO1_config, FLEXIO1_CLK_FREQ);
  /* Enable interrupt FLEXIO1_IRQn request in the NVIC */
  EnableIRQ(FLEXIO1_IRQn);
}

/***********************************************************************************************************************
 * LPSPI1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI1'
- type: 'lpspi'
- mode: 'transfer'
- custom_name_enabled: 'false'
- type_id: 'lpspi_6e21a1e0a09f0a012d683c4f91752db8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI1'
- config_sets:
  - transfer:
    - config:
      - transmitBuffer:
        - init: 'true'
      - receiveBuffer:
        - init: 'true'
      - dataSize: '10'
      - flags: 'kLPSPI_MasterPcs0 kLPSPI_MasterPcsContinuous'
      - callback:
        - name: ''
        - userData: ''
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - master:
      - baudRate: '5000000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - dataOutConfig: 'kLpspiDataOutRetained'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI1_config = {
  .baudRate = 5000000,
  .bitsPerFrame = 8,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000,
  .lastSckToPcsDelayInNanoSec = 1000,
  .betweenTransferDelayInNanoSec = 1000,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .dataOutConfig = kLpspiDataOutRetained
};
lpspi_transfer_t LPSPI1_transfer = {
  .txData = LPSPI1_txBuffer,
  .rxData = LPSPI1_rxBuffer,
  .dataSize = 10,
  .configFlags = kLPSPI_MasterPcs0 | kLPSPI_MasterPcsContinuous
};
lpspi_master_handle_t LPSPI1_handle;
uint8_t LPSPI1_txBuffer[LPSPI1_BUFFER_SIZE];
uint8_t LPSPI1_rxBuffer[LPSPI1_BUFFER_SIZE];

void LPSPI1_init(void) {
  LPSPI_MasterInit(LPSPI1_PERIPHERAL, &LPSPI1_config, LPSPI1_CLOCK_FREQ);
  LPSPI_MasterTransferCreateHandle(LPSPI1_PERIPHERAL, &LPSPI1_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * PIT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PIT'
- type: 'pit'
- mode: 'LPTMR_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'pit_a4782ba5223c8a2527ba91aeb2bc4159'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PIT'
- config_sets:
  - fsl_pit:
    - enableRunInDebug: 'false'
    - enableSharedInterrupt: 'true'
    - sharedInterrupt:
      - IRQn: 'PIT_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - timingConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - channels:
      - 0:
        - channel_id: 'CHANNEL_0'
        - channelNumber: '3'
        - enableChain: 'false'
        - timerPeriod: '0.005s'
        - startTimer: 'true'
        - enableInterrupt: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const pit_config_t PIT_config = {
  .enableRunInDebug = false
};

void PIT_init(void) {
  /* Initialize the PIT. */
  PIT_Init(PIT_PERIPHERAL, &PIT_config);
  /* Set channel 3 period to 5 ms (312500 ticks). */
  PIT_SetTimerPeriod(PIT_PERIPHERAL, PIT_CHANNEL_0, PIT_CHANNEL_0_TICKS);
  /* Enable interrupts from channel 3. */
  PIT_EnableInterrupts(PIT_PERIPHERAL, PIT_CHANNEL_0, kPIT_TimerInterruptEnable);
  /* Enable interrupt PIT_IRQN request in the NVIC */
  EnableIRQ(PIT_IRQN);
  /* Start channel 3. */
  PIT_StartTimer(PIT_PERIPHERAL, PIT_CHANNEL_0);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(DMA0_DMAMUX_BASEADDR);
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  FLEXIO1_init();
  LPSPI1_init();
  PIT_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
