/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_WAKA_MSG_PB_H_INCLUDED
#define PB_WAKA_MSG_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _WakaFrameFlags {
    WakaFrameFlags_Ack = 0,
    WakaFrameFlags_Nack = 1
} WakaFrameFlags;

/* Struct definitions */
typedef struct _WakaMessage {
    pb_callback_t device_name;
    pb_callback_t text;
} WakaMessage;

typedef PB_BYTES_ARRAY_T(128) WakaFrame_payload_t;
typedef struct _WakaFrame {
    int32_t seq;
    int32_t ack;
    int32_t size;
    WakaFrameFlags flags;
    WakaFrame_payload_t payload;
} WakaFrame;


/* Helper constants for enums */
#define _WakaFrameFlags_MIN WakaFrameFlags_Ack
#define _WakaFrameFlags_MAX WakaFrameFlags_Nack
#define _WakaFrameFlags_ARRAYSIZE ((WakaFrameFlags)(WakaFrameFlags_Nack+1))


/* Initializer values for message structs */
#define WakaFrame_init_default                   {0, 0, 0, _WakaFrameFlags_MIN, {0, {0}}}
#define WakaMessage_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}}
#define WakaFrame_init_zero                      {0, 0, 0, _WakaFrameFlags_MIN, {0, {0}}}
#define WakaMessage_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define WakaMessage_device_name_tag              1
#define WakaMessage_text_tag                     2
#define WakaFrame_seq_tag                        1
#define WakaFrame_ack_tag                        2
#define WakaFrame_size_tag                       3
#define WakaFrame_flags_tag                      4
#define WakaFrame_payload_tag                    5

/* Struct field encoding specification for nanopb */
#define WakaFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    seq,               1) \
X(a, STATIC,   SINGULAR, INT32,    ack,               2) \
X(a, STATIC,   SINGULAR, INT32,    size,              3) \
X(a, STATIC,   SINGULAR, UENUM,    flags,             4) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           5)
#define WakaFrame_CALLBACK NULL
#define WakaFrame_DEFAULT NULL

#define WakaMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_name,       1) \
X(a, CALLBACK, SINGULAR, STRING,   text,              2)
#define WakaMessage_CALLBACK pb_default_field_callback
#define WakaMessage_DEFAULT NULL

extern const pb_msgdesc_t WakaFrame_msg;
extern const pb_msgdesc_t WakaMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WakaFrame_fields &WakaFrame_msg
#define WakaMessage_fields &WakaMessage_msg

/* Maximum encoded size of messages (where known) */
#define WakaFrame_size                           166
/* WakaMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
